# 站点配置
title: 风清扬的博客
email: your-email@example.com # 替换为你的邮箱
description: >- # 这是网站的描述，会显示在搜索引擎结果中
  风清扬的博客，记录生活，分享技术，品味人生。
baseurl: "52db.github.io" # 如果你的仓库名不是 username.github.io，例如是 your_repo_name，则需要设置为 "/your_repo_name"。否则保持为空。
url: "https://52db.github.io" # 替换为你的 GitHub Pages 域名，例如 https://your-username.github.io

# 构建设置
markdown: kramdown
highlighter: rouge # 代码高亮
kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter_opts:
    block:
      line_numbers: true # 代码块显示行号

# 分页设置
paginate: 5 # 每页显示的文章数量
paginate_path: "/page:num/" # 分页链接路径

# Jekyll 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate # 添加分页插件

# 默认设置 (为所有文章和页面设置默认布局)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:year/:month/:day/:title/" # 自定义文章链接结构

# 排除不需要的文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
