title: 风清扬博客
description: 分享生活、技术与思考
url: https://52db.github.io
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page:num/"
